name: default_workflow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        env: # Or as an environment variable
          big__secret: ${{ secrets.bigsecret }}
        run: |
          echo ls -lh
          echo "$big__secret"
