name: default_workflow
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        env: 
          BIGSECRET: ${{ secrets.BIGSECRET }}
        run: |
          echo ls -lh
          echo "$BIGSECRET"
